name: Docker Image CI - dotnet-api-template

on: push

env:
  APP_NAME: dotnet-api-template

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/$APP_NAME:latest
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$APP_NAME
